# Site settings
baseurl = "https://www.violatedbygoogle.com"
languageCode = "en-us"
title = "Violated by Google"
theme = "spectre-pixel-custom"

enableRobotsTXT = true
disableKinds = ["taxonomy", "term", "RSS"]

[minify]
  disableXML = true
  # minifyOutput = true

[params]
  author = "Marc T0K_ D."
  description = "All the times Google forgot not **to be evil**"
  explicitdescription = "Non-exhaustive list of the privacy/tax/etc. violations committed by Google"

  enableRSS = false
  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = []
  customJS  = []
  

  # The variables below are optionally too and can be used to
  # translate or customize each string of the theme.


	# Pagination links
	olderPosts = ""
	newerPosts = ""
	copyright = ""

	# 404 page
	title404 = ""
	subtitle404 = ""

  github   = "https://github.com/MarcT0K/ViolatedByGoogle"

  keywords = ["Google", "Privacy", "Antitrust", "Monopoly", "Fine", "European Union", "Settlement"]

