name = "Customized Spectre Theme"
license = "MIT"
licenselink = "https://github.com/MarcT0K/ViolatedByGoogle/blob/main/themes/spectre-pixel-custom/LICENSE.md"
description = "Minimal Material theme with a timeline"
homepage = "https://github.com/MarcT0K/ViolatedByGoogle/tree/main/themes/spectre-pixel-custom"
tags = ["modern design", "timeline", "blog", "portfolio", "resume", "responsive", "pixel", "font awesome", "spectre css framework", "devicon", "google analytics", "rss", "syntax highlighting", "pagination"]
features = ["modern design", "timeline", "blog", "portfolio", "resume", "responsive", "pixel", "font awesome", "spectre css framework", "devicon", "google analytics", "rss", "syntax highlighting", "pagination"]
min_version = "0.41"

[author]
  name = "Marc D."
  homepage = "https://marc.damie.eu"

[original]
  # Inspired by Cactus theme
  name = "Spectre Pixel Theme"
  author = "Shin Tatt"
  repo = "https://github.com/st-wong/hugo-spectre-pixel-theme"
